package com.yunxi.phone.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.xutils.db.annotation.Column;
import org.xutils.db.annotation.Table;

/**
 * Entity mapped to table "DOWNLOAD".
 */
@Table(name = "downloadmax")
public class DownloadMax {
    @Column(name = "id", isId = true)
    private Long id;
    /**
     * Not-null value.
     */
    @Column(name = "download_url")
    private String download_url;

    public String getDownload_url() {
        return download_url;
    }
    public void setDownload_url(String download_url) {
        this.download_url = download_url;
    }


    public DownloadMax() {
    }

    public DownloadMax(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
