package com.yunxi.phone.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.xutils.db.annotation.Column;
import org.xutils.db.annotation.Table;

/**
 * Entity mapped to table "DOWNLOAD".
 */
@Table(name="download_info")
public class DownloadInfo {
    @Column(name="id",isId = true)
    private Long id;
    /**
     * Not-null value.
     */
    @Column(name="download_url")
    private String download_url;
    /**
     * Not-null value.
     */
    @Column(name="file_url")
    private String file_url;
    /**
     * Not-null value.
     */
    @Column(name="file_name")
    private String file_name;
    @Column(name="finished")
    private Long finished;
    @Column(name="total")
    private Long total;
    @Column(name="progress")
    private Integer progress;
    @Column(name="status")
    private Integer status;

    public DownloadInfo() {
    }

    public DownloadInfo(Long id) {
        this.id = id;
    }

    public DownloadInfo(Long id, String download_url, String file_url, String file_name, Long finished, Long total, Integer progress, Integer status) {
        this.id = id;
        this.download_url = download_url;
        this.file_url = file_url;
        this.file_name = file_name;
        this.finished = finished;
        this.total = total;
        this.progress = progress;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDownload_url() {
        return download_url;
    }

    public void setDownload_url(String download_url) {
        this.download_url = download_url;
    }

    public String getFile_url() {
        return file_url;
    }

    public void setFile_url(String file_url) {
        this.file_url = file_url;
    }

    public String getFile_name() {
        return file_name;
    }

    public void setFile_name(String file_name) {
        this.file_name = file_name;
    }

    public Long getFinished() {
        return finished;
    }

    public void setFinished(Long finished) {
        this.finished = finished;
    }

    public Long getTotal() {
        return total;
    }

    public void setTotal(Long total) {
        this.total = total;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
